akademik/urls.py
from django.urls import path
from . import views

app_name = "akademik"

urlpatterns = [
    path("", views.indexView, name="index"),
    path("<int:fakultas_id>", views.detailView, name="detail"),
    path("create/", views.createView, name="create"),
    path("update/<int:fakultas_id>", views.updateView, name="update"),
    path("delete/<int:fakultas_id>", views.deleteView, name="delete"),
]

kampusdemo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("akademik/", include("akademik.urls")),
]

akademik/models.py
from django.db import models


# Create your models here.
class Fakultas(models.Model):
    nama_fakultas = models.CharField(max_length=150, null=True)
    prodi = models.CharField(max_length=150, null=True)

    def __str__(self):
        return self.nama_fakultas

    class Meta:
        db_table = "fakultas"

akademik/forms.py
# from django.forms import ModelForm
from django import forms

from .models import Fakultas


class FakultasForm(forms.Form):
    nama_fakultas = forms.CharField(
        label="Nama Fakultas", widget=forms.TextInput(attrs={"class": "form-control"})
    )
    prodi = forms.CharField(
        label="Program Studi", widget=forms.TextInput(attrs={"class": "form-control"})
    )

    class Meta:
        model = Fakultas

        fields = ("nama_fakultas", "prodi")

akademik/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib import messages

from .models import Fakultas
from .forms import FakultasForm


# Create your views here.
def indexView(request):
    fakultas = Fakultas.objects.all()

    return render(request, "fakultas/index.html", {"fakultas": fakultas})


def detailView(request, fakultas_id):
    try:
        fakultas = Fakultas.objects.get(pk=fakultas_id)
        context = {"fakultas": fakultas}
    except Fakultas.DoesNotExist:
        raise HttpResponse("fakultas tidak ditemukan !!!")

    return render(request, "fakultas/detail.html", context)


def createView(request):
    if request.method == "POST":
        form = FakultasForm(request.POST)

        if form.is_valid():
            nama_fakultas = form.cleaned_data["nama_fakultas"]
            prodi = form.cleaned_data["prodi"]
            Fakultas.objects.create(
                nama_fakultas=nama_fakultas,
                prodi=prodi,
            )

            messages.success(request, "Data berhasil disimpan!!!")
            return redirect("akademik:index")
    else:
        form = FakultasForm()

    return render(request, "fakultas/form.html", {"form": form})


def updateView(request, fakultas_id):
    try:
        fakultas = Fakultas.objects.get(pk=fakultas_id)
    except Fakultas.DoesNotExist:
        raise HttpResponse("Fakultas tidak ditemukan!!!")

    if request.method == "POST":
        form = FakultasForm(request.POST)
        if form.is_valid():
            fakultas.nama_fakultas = form.cleaned_data["nama_fakultas"]
            fakultas.prodi = form.cleaned_data["prodi"]
            fakultas.save()

            messages.success(request, "Data berhasil diubah!!!")
            return redirect("akademik:index")
    else:
        form = FakultasForm(
            initial={"nama_fakultas": fakultas.nama_fakultas, "prodi": fakultas.prodi}
        )

    return render(request, "fakultas/form.html", {"form": form})


def deleteView(request, fakultas_id):
    try:
        fakultas = Fakultas.objects.get(pk=fakultas_id)
        fakultas.delete()

        messages.success(request, "Data berhasil dihapus!!!")
        return redirect("akademik:index")

    except Fakultas.DoesNotExist:
        raise ("Fakultas tidak ditemukan !!!")

akademik/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Kampus</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
    
    {% block content %}
    {% endblock %}

    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

akademik/templates/fakultas/detail.html
{% extends 'base.html' %}
{% block content %}
    
    <div class="container">
        <div class="row justify-content-center mt-5">
            <div class="col-md-10">

                <h1>Detail Fakultas Akademik</h1>

                <ul class="list-group">
                    <li class="list-group-item list-group-item-primary">Keterangan</li>
                    <li class="list-group-item"><b>Nama Fakultas : </b>{{fakultas.nama_fakultas}}</li>
                    <li class="list-group-item"><b>Program Studi : </b>{{fakultas.prodi}</li>
                </ul>

                <a href="{% url 'akademik:index' %}" class="btn btn-primary mt-3">
                    Kembali
                </a>
            </div>
        </div>
    </div>

{% endblock %}

akademik/templates/fakultas/form.html
{% extends 'base.html' %}
{% block content %}
    
    <div class="container">
        <div class="row justify-content-center mt-5">
            <div class="col-md-10">

                <h1>Form Fakultas</h1>

                <form method="post">
                    {% csrf_token %}
                    {% load widget_tweaks %}

                    <div class="form-group">
                        {{ form.as_p }}
                    </div>

                    <!-- <div class="form-group">
                        <label for="">Nama Fakultas</label>
                        {{ form.nama_fakultas|add_class:"form-control" }}
                    </div> -->

                    <div class="form-group">
                        <button class="btn btn-success">Submit</button>
                        <a href="{% url 'akademik:index' %}" class="btn btn-primary">Kembali</a>
                    </div>
                </form>

            </div>
        </div>
    </div>

{% endblock %}

akademik/templates/fakultas/index.html
{% extends 'base.html' %}

{% block content %}
<div class="container">

    <div class="row justify-content-center mt-5">
        <div class="col-md-10">
    
            <h1>Daftar Fakultas</h1>
            
            <a href="{% url 'akademik:create' %}" class="btn btn-primary">Tambah Fakultas Baru</a>

            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>Nama Fakultas</th>
                        <th>Program Studi</th>
                        <th>Aksi</th>
                    </tr>
                </thead>
                <tbody>
                    {% for fk in fakultas %}
                    <tr>
                        <td>{{fk.nama_fakultas}}</td>
                        <td>{{fk.prodi}}</td>
                        <td>
                            <a href="{% url 'akademik:detail' fk.id %}" class="btn btn-info text-white">Detail</a>
                            <a href="{% url 'akademik:update' fk.id %}" class="btn btn-warning text-white">Ubah</a>
                            <a href="{% url 'akademik:delete' fk.id %}" class="btn btn-danger" onclick="return confirm('Apakah anda ingin menghapus {{fk.nama_fakultas}} ? ')">Hapus</a>
                        </td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="3">Data Masih Kosong!!!</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>

        </div>
    </div>
</div>
{% endblock %}